# Generated by Django 4.1 on 2024-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
